### ISSUE TITLE
 CacheRegion: invalidation from another process

### ISSUE THREAD

**Issue by keipaglows** [sqlalchemy/dogpile.cache#138]
I apologize for discussing a question in the issues section, but I didn't find a better place to ask about it.

I'm trying to achieve cache region invalidation outside of the main project via console script. As documentation states: ```It (invalidate method) does not impact other Python processes or regions as the timestamp is only stored locally in memory```, so it doesn't suppose to work like this at all. 

There is a hint in documentation as well: ```To implement invalidation where the timestamp is stored in the cache or similar so that all Python processes can be affected by an invalidation timestamp, implement a custom RegionInvalidationStrategy```

It feels weird to me storing timestamp in a cache for purpose of getting another piece of cache to invalidate. Are there any other possible directions to achieve such effect of invalidating region through another process?

Another question I have is - how to keep cached data intact after application restart? I would assume answer for both of my questions comes from the same problem.

Once again, sorry if this is not a proper place to ask.

**Comment by jvanasco** [comment]
First: well over 9/10 times, people don't need to do a true invalidation of a region - a hard delete is good enough.

If you're using Redis as the backing storage (Memcached should work too), a trick I use is to define a`key_mangler` for each region which sets a unique prefix (usually it's `{unique_letter_or_number}|{key}`).  That lets me easily query the backend for each region's keys and delete them.

I do a hard delete because of how dogpile cache data is implemented.  Dogpile doesn't actually cache your data, but a pickled object which contains metadata (timestamp, dogpile version, etc) and your actual data in a nested structure.  The library validates your payload based on the metadata's timestamp, and returns the nested structure.

If you really really really need to do a true invalidation on the region, where the expired data is still available)... 

using this trick, you'd need to write a tool that can iterate the region's keys based on prefix, retrieve and edit their expiry timestamps in python, then store them back in the data store. 

another option is to abuse dogpile and write a custom backend and serializer, which you use to store a private 'object_version' id in the metadata.  your application can then periodically check a file/service/etc to fetch the active minimum object_version.  if there is a mismatch, you can then edit the timestamp which dogpile looks for and set it to something which will trigger regeneration (IIRC, that works better than raising a RegenerationException).  This works very well, but it's definitely in the realm of "advanced and may break".

I wrote an example of the custom serializer on the readme of my dogpile debugtoolbar panel for pyramid.  https://github.com/jvanasco/pyramid_debugtoolbar_dogpile   Basically you'd want to adjust the "ct" time instead of tracking the size. an example of a custom backend that allows for swappable serializers is in my custom redis backend : https://github.com/jvanasco/dogpile_backend_redis_advanced

These are rather complicated ways to achieve the result - but the vast majority of users do not cache the type or volumes of data where "invalidation" is noticeably better than "deletion".

**Comment by keipaglows** [comment]
> github gives us the "question" tag so I finally don't have to worry about mailing lists for every project, you're good ! :)
> 

I'm glad that such tag exists now :slightly_smiling_face:  Thank you guys for such insightful and detailed response.  I was able to solve both of my problems.

With the first one I've decided to just go with console scripts that use redis-cli directly. Kind of lazy, I guess, but for now it should work.

Regarding data loss - I do actually use redis as a cache backend. It's the former problem that led me to think it has something to do with timestamps inside process. I found a bug in my `function_key_generator` method, that made cache key names inconsistent. Now it works just fine.

> If you're using Redis as the backing storage (Memcached should work too), a trick I use is to define a`key_mangler` for each region which sets a unique prefix (usually it's `{unique_letter_or_number}|{key}`). That lets me easily query the backend for each region's keys and delete them.

I was trying to figure out first how would custom `key_mangler` and `region_invalidator` help to solve this problem. Unfortunately I wasn't able to come up with fast solution, and I've decided to go with a more "friendly" hard delete.

Again, thank you guys! It was great to have such helpful responses from you.
