### ISSUE TITLE
Is lock released on redis when app is killed ?

### ISSUE THREAD

**Issue by loic-seguin** [sqlalchemy/dogpile.cache#261]
Hello,

I am using this configuration : 

```
region = make_region().configure('dogpile.cache.redis',
    arguments = {
        'host': localhost,
        'port': 6379,
        'db': 0,
        'redis_expiration_time': int(os.environ.get("TTL_REDIS_CACHE", "60")),
        'distributed_lock': True,
        'thread_local_lock': False,
        'lock_timeout' : 10,
        'socket_timeout': 10,
        'socket_connect_timeout': 10
        }
    )
```

I was wondering what is happening if a distributed lock is set on redis side and the pod (I am using openshift), is killed what is happening ?

Is there a kind of shutdown hook to release the lock before the app is being killed ? Or any other system that ensures that we don't leave a lock not released on redis side ?

Thx for your support !

**Comment by loic-seguin** [comment]
Well, on Redisson library implemented in java, their implementation is managing this case https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/RedissonLock.java.

The comments at the beggining of the class are saying this : 
```
/**
 * Distributed implementation of {@link java.util.concurrent.locks.Lock}
 * Implements reentrant lock.<br>
 * Lock will be removed automatically if client disconnects.
 * <p>
 * Implements a <b>non-fair</b> locking so doesn't guarantees an acquire order.
 *
 * @author Nikita Koksharov
 *
 */
```

So you mean that if the lock call is working and then the app crashes, the lock is not released ?
Maybe the lock_timeout value is enough if fact...If the lock has been set and is still there more than the lock_timeout then the lock is released no ?

**Comment by zzzeek** [comment]
dogpile doesnt have any kind of process / thread / signal listener that does anything like that, and if we're talking about an app crashing, I dont think there's any way that it could either, because even if you had a signal handler, if the Python process crashed, it crashed.      

the java comment you refer to above seems to indicate it's doing lock removal based on client disconnection, not crashing.   which is fine.    

but again, dogpile does not implement this lock.  it's implemented [here](https://github.com/redis/redis-py/blob/master/redis/lock.py).  so the best source of information on how this lock works and how it should be used would be the py-redis team at https://github.com/redis/redis-py/issues .

**Comment by loic-seguin** [comment]
Ok I understood, thx for your support !
